apiVersion: v1
name: expose
home: https://jenkins-x.github.io/jenkins-x-website/
version: 1.0.7
icon: https://raw.githubusercontent.com/fabric8-apps/exposecontroller-app/master/src/main/fabric8/icon.png
maintainers:
- name: Jenkins X Team
  email: jenkins-x@googlegroups.com