env:
  MICROSERVICE_GATEWAY_BASEURL: '{{ tpl .Values.global.peeq.url $ }}'
  SPRING_RABBITMQ_HOST: '{{ .Release.Name }}-rabbitmq'
extraEnv:
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        key: rabbitmq-username
        name: rabbitmq
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: rabbitmq-password
        name: rabbitmq
livenessProbe:
  initialDelaySeconds: 120
persistence:
  accessMode: ReadWriteMany
  enabled: true
  size: 50Gi
  storageClass: nfs-client
  existingClaim: jx-peeq-content
postgres:
  enabled: true
  name: peeq-postgres
  hostname: peeq-postgres-postgresql

