env:
  MICROSERVICE_GATEWAY_BASEURL: '{{ tpl .Values.global.peeq.url $ }}'
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-peeq-postgres:5432/peeqdwolladb
  SPRING_DATASOURCE_USERNAME: postgres
  VELOCITYZ_PAYMENT_DWOLLA_PRODUCTION: "false"
  VELOCITYZ_PAYMENT_DWOLLA_SUBSCRIBE_WEBHOOKS: "false"
  VELOCITYZ_PAYMENT_DWOLLA_WEBHOOK_URL: '{{ tpl .Values.global.peeq.url $ }}/api/dwolla/webhook'
  SPRING_RABBITMQ_HOST: '{{ .Release.Name }}-rabbitmq'
envFrom:
  - secretRef:
      name: peeq-dwolla
extraEnv:
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: postgresql-password
        name: '{{ .Release.Name }}-peeq-postgres'
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        key: rabbitmq-username
        name: rabbitmq
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: rabbitmq-password
        name: rabbitmq
