livenessProbe:
  initialDelaySeconds: 120
env:
  SPRING_RABBITMQ_HOST: '{{ .Release.Name }}-rabbitmq'
extraEnv:
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        key: rabbitmq-username
        name: rabbitmq
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: rabbitmq-password
        name: rabbitmq
