env:
  JAVA_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=1098 -Dcom.sun.management.jmxremote.rmi.port=1098 -Djava.rmi.server.hostname=127.0.0.1
  MICROSERVICE_GATEWAY_BASEURL: '{{ tpl .Values.global.peeq.url $ }}'
  RECORDING_URL_TEMPLATE: '{{ tpl .Values.global.rtmp.http.url $ }}/vod/%s.mp4'
  SPRING_REDIS_HOST: jx-staging-peeq-redis-master
  SPRING_REDIS_PORT: 6379
  SPRING_RABBITMQ_HOST: jx-staging-rabbitmq
  SPRING_JPA_SHOW_SQL: "false"
extraEnv:
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        key: rabbitmq-username
        name: rabbitmq
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: rabbitmq-password
        name: rabbitmq
  - name: SPRING_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: redis-password
        name: peeq-redis
livenessProbe:
  initialDelaySeconds: 120
postgres:
  hostname: jx-staging-peeq-postgres
  secretName: jx-staging-peeq-postgres
  ddlAuto: validate
  enabled: true
resources:
  limits:
    cpu: 1000m
    memory: 2048Mi