existingSecret: rabbitmq
persistentVolume:
  enabled: true
  size: 20Gi
prometheus:
  operator:
    enabled: false
rabbitmqMemoryHighWatermark: 1500MB
rbac:
  create: true
replicaCount: 2
resources:
  requests:
    cpu: 1000m
    memory: 2048Mi
service:
  annotations:
    fabric8.io/annotations: |
      kubernetes.io/ingress.class: nginx
    fabric8.io/expose: "true"
  clusterIP: None
