---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bindplane-collector-config
data:
  COLLECTOR_NAME: K8s Staging Collector
  API_ADDRESS: https://production.api.bindplane.bluemedora.com
  BINDPLANE_HOME: /opt/bluemedora/bindplane-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: BindPlane collector
  labels:
    app: bindplane-collector
    product: bindplane
  name: collector
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bindplane-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: Collector for bindplane
      labels:
        app: bindplane-collector
        product: bindplane
      name: bindplane-collector
    spec:
      containers:
        - args:
            - "/opt/bluemedora/bindplane-collector/scripts/run_collector_in_docker.sh"
          command:
            - sh
          image: docker.io/bluemedora/bindplane-metrics-collector:latest
          imagePullPolicy: Always
          name: bindplane-collector
          resources:
            limits:
              memory: "4096Mi"
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: jx-staging-bindplane-collector
            - configMapRef:
                name: bindplane-collector-config
          volumeMounts:
            - mountPath: /opt/bluemedora/bindplane-collector/tmp
              name: tmp
            - mountPath: /opt/bluemedora/bindplane-collector/downloadedPlugins
              name: downloadedplugins
            - mountPath: /opt/bluemedora/bindplane-collector/log
              name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmp
          emptyDir: {}
        - name: downloadedplugins
          emptyDir: {}
        - name: log
          emptyDir: {}