{{- if .Values.expose }}
{{- if .Values.expose.config }}
{{- if .Values.expose.config.tlsacme }}
{{- if eq .Values.expose.config.tlsacme "true" }}
{{- if .Values.expose.production }}
{{- $issuerName := .Values.expose.production | ternary "letsencrypt-prod" "letsencrypt-staging" -}}
{{- $domain := .Values.expose.config.domain }}
{{- $tlsSecretName := .Values.expose.config.tlsSecretName -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ $issuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email | default "fake@email.com"}}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ $issuerName }}
    solvers:
    - selector:
        dnsNames:
        - "*.{{ $domain }}"
        - "{{ $domain }}"
        - "*.api-jx-staging.{{ $domain }}"
        - "*.peeq-celeb-fe-jx-staging.{{ $domain }}"
      # ACME DNS-01 provider configurations
      dns01:
{{ tpl (toYaml .Values.acme.dns01 ) . | indent 8 }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $tlsSecretName }}"
spec:
  secretName: "{{ $tlsSecretName }}"
  issuerRef:
    name: {{ $issuerName }}
  commonName: "*.{{ $domain }}"
  dnsNames:
  - "*.{{ $domain }}"
  - "{{ $domain }}"
  - "*.api-jx-staging.{{ $domain }}"
  - "*.peeq-celeb-fe-jx-staging.{{ $domain }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
