dependencies:
- name: celeb-meet-greet-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.99
- name: celeb-onboarding-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
- name: fan-meet-greet-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.69
- name: handler-meet-greet-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.50
- name: handler-onboarding-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- alias: identity
  name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 8.0.0
- name: peeq-broadcast
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.49
- name: peeq-broadcast-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: peeq-celebrity
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: peeq-charity
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: peeq-content
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
- name: peeq-dwolla
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.26
- name: peeq-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: peeq-fan
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.61
- name: peeq-handler-broadcast-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: peeq-inventory
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.90
- name: peeq-media
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.83
- name: peeq-message-board
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.55
- name: peeq-notification-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: peeq-purchase-request-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: peeq-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.561
- name: peeq-recommendation-engine
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: peeq-recording-meet-greet-keepsake-videos-bpm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: peeq-sms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- name: peeq-sse
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.58
- name: peeq-stream
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.60
- name: peeq-stripe
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.10
- name: peeq-subscriptions
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: peeq-tags
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.23
- name: peeq-users
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: peeq-wallet
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.25
- alias: peeq-postgres
  name: postgresql
  repository: https://charts.helm.sh/stable
  version: 6.3.9
- alias: rabbitmq
  name: rabbitmq-ha
  repository: https://charts.helm.sh/stable
  version: 1.46.4
- alias: peeq-redis
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 12.7.4
